#!/bin/bash
echo "Alle Texte zuruecksetzen? Schreibe j oder n und bestaetige:"
read shouldreplace
if [ "$shouldreplace" = "j" ]
then
  echo "Verbindung..."
  wget -q --spider --timeout=8 --tries=2 https://github.com/pdistolfo-b
  if [ $? -eq 0 ]; then
    cd ~/Dokumente/x; git fetch --quiet
    if [ $(git rev-parse HEAD) != $(git rev-parse @{u}) ]; then
      echo "Update erforderlich! Mit Enter bestaetigen."
      read 
      git pull --quiet
      chmod 0700 Texte-Zuruecksetzen
      mv Texte-Zuruecksetzen ..
      ../Texte-Zuruecksetzen
      exit
    else
      git pull
      cp *.docx ~/Schreibtisch
      cp *.png ~/.local/share/backgrounds
      echo "OK."
    fi
  else
    echo "Keine Verbindung zum Server."
    read
  fi
fi
echo "Bitte schliessen."

